### ISSUE TITLE
winrate drops to 0

### ISSUE THREAD

**Issue by DoveDoof** [DoveDoof/QLUT#5]
Figure out why the winrate drops to zero at high learning rate and fix it.
Maybe neuron weights are diverging or different network settings are needed.

In the case of divirging weights, maybe add regularization?
In any case, try to catch it.
Maybe automatic detection?

**Comment by DoveDoof** [comment]
Maybe not really a bug, more of an anomoly

**Comment by Mark-Boon** [comment]
The weights are not dropping to zero or go to infinity

**Comment by DoveDoof** [comment]
Making test game player against network

**Comment by Mark-Boon** [comment]
The original TicTacToe game experiences the same 'bug' when the parameters are set properly. For example: layers 81,81,81 and learn rate 1e-1, batch size 1000 also ends up having a win rate of 0.

There seems to be a turning point from where it can still 'save himself' from having a 0 win rate for the future. Using learn rate 7e-2 is still doable for ttt.

**Comment by Mark-Boon** [comment]
While reading more about the methods used for AlphaZero I found out that using only self-play with a RL agent tends to becomes instable in general (using the widely used policy gradient and q learning methods). Therefore, AlphaZero uses other techniques. Maybe interesting to do something with that? 

https://www.reddit.com/r/MachineLearning/comments/76xjb5/ama_we_are_david_silver_and_julian_schrittwieser/
