### ISSUE TITLE
fix historic playing

### ISSUE THREAD

**Issue by DoveDoof** [DoveDoof/QLUT#6]
policy gradient historic doesnt work

**Comment by DoveDoof** [comment]
still use number of games as stopping criteria in case the agent does not improve

**Comment by Mark-Boon** [comment]
Current bug:
When playing network vs network, at some point during learning the warning 'mini batch std = 0' starts appearing. All rewards of playing the game are 0, so std = 0. The UTTT games are still played (around 30 moves per game) but at some point the bots stop playing while there are still available moves, as if they come to a draw.

**Comment by DoveDoof** [comment]
Maybe the random generators are seeded prior to each game, this might be a the cause of the repeated games?
As far as the game engine, this needs to fixed asap.

**Comment by Mark-Boon** [comment]
Found the bug for 'we have a winner' text:
if X wasn't the winner, it automatically printed that O is the winner instead (so also when it would end up being draw). This explains the engine saying O wins, but reward = 0.
